#!/usr/bin/env bash

HERE="$( cd -P "$( dirname "$0" )" && pwd )"
THISBIN="$(basename $0)"
cd "$HERE"
set -e
source $HERE/password.functions
SIZE=3 
REPS=1
DICT=/usr/share/dict/words
if [[ ! -e ${DICT} ]];then
    cd /usr/share/dict
    wget -q https://down.fdos.me/words
fi
PASSTYPE="easy"

while getopts "hs:r:d:ETLR" opt; do
    case $opt in
        h) echo "usage: $THISBIN -s size_in_chars -r number_of_iterations [-d dictionary_file] [-{E|T|L|R}]";
           echo "    -s <chars>: the minimum size in chars of the password.  Default: 3"
           echo "    -r <reps>: The number of words to spit out.  Default: 1"
           echo "    -d <dict_file>: File of words to choose from.  Default: /usr/share/dict/words"
           echo "    -E: easily touch typeable (default, real words)"
           echo "    -T: tivo style password - easily typable onscreen (no real words)"
           echo "    -L: words that you can touchtype with your left hand only (real words)"
           echo "    -R: words that you can touchtype with your right hand only (real words)"
           exit 2
           ;;
        d) DICT="$OPTARG"                ;;
        s) SIZE="$OPTARG"                ;;
        r) REPS="$OPTARG"                ;;
        L) PASSTYPE="left"               ;;
        R) PASSTYPE="right"              ;;
        T) PASSTYPE="tivo"               ;;
        E) PASSTYPE="easy"               ;;
        *) echo "invalid argument"; exit -1 ;;
    esac
done
shift $((OPTIND - 1))

WORDS=/tmp/password.${RANDOM}.$$
touch $WORDS
trap "rm $WORDS 2>/dev/null" EXIT

tivo_word() {
    local alphabet=(a b c d e f g h i j k l m n o p q r s t u v w x y z)
    local t=${alphabet[$((RANDOM % ${#alphabet[@]}))]}
    local ret=""
    for i in $(seq "$SIZE"); do
        ret=${ret}${t}
        eval "t=$(fun_${t})"
    done
    echo $ret
}

random_word() {
    for i in $(seq $REPS); do
        perl -ne 'rand($.) < 1 && ($l = $_) while <>; print $l;' < $WORDS
    done
}


case "$PASSTYPE" in
    easy) (egrep -i '^([qwerasdfzxcv][uiopjklm])+$' ${DICT}; \
           egrep -i '^([uiopjklm][qwerasdfzxcv])+$' ${DICT}) \
              | tr '[:upper:]' '[:lower:]' \
              | sort -u \
              | awk "length(\$0) > $SIZE {print \$0}" > ${WORDS};
          random_word
          ;;

    left) egrep -i '^[qwertyasdfgzxcvb]+$' ${DICT} \
                      | tr '[:upper:]' '[:lower:]' \
                      | sort -u \
                      | awk "length(\$0) > $SIZE {print \$0}" > ${WORDS};
                      random_word
                      ;;

    right) egrep -i '^[yuiophjklnm]+$' ${DICT} \
                      | tr '[:upper:]' '[:lower:]' \
                      | sort -u \
                      | awk "length(\$0) > $SIZE {print \$0}" > ${WORDS};
                      random_word
                      ;;

    tivo) for i in $(seq $REPS); do tivo_word; done ;;

    *) usage Unknown password type $PASSTYPE ;;
esac
