#!/bin/bash
export PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

#Check Root
[ $(id -u) != "0" ] && { echo "Error: You must be root to run this script"; exit 1; }

if [[ -e "/usr/local/SSR-Bash-Python/update.txt" ]];then
	echo ""
	cat /usr/local/SSR-Bash-Python/update.txt
	read -n 1 -p "任意键退出" any
	if [[ -e /usr/local/SSR-Bash-Python/oldupdate.txt ]];then
		rm -f /usr/local/SSR-Bash-Python/oldupdate.txt
	fi
	mv /usr/local/SSR-Bash-Python/update.txt /usr/local/SSR-Bash-Python/oldupdate.txt
fi
PID=$(ps -ef |grep -v grep | grep "bash" | grep "servercheck.sh" | grep "run" | awk '{print $2}')
if [[ -z $PID ]];then
	if [[ -e /usr/local/SSR-Bash-Python/check.log ]];then
		nohup bash /usr/local/SSR-Bash-Python/servercheck.sh run 2>/dev/null &
	fi
fi

#Check log
if [[ -e /usr/local/shadowsocksr/ssserver.log ]];then
log_max=$((10*1024))
log_filesize=$(du /usr/local/shadowsocksr/ssserver.log | awk -F' ' '{ print $1 }')
if [[ ${log_filesize} -ge ${log_max} ]];then
    sed -i -n '1,198N;$p;N;D' /usr/local/shadowsocksr/ssserver.log
fi
fi

yiyan(){
nowdate=$(date +%Y-%m-%d)
if [[ ! -e /tmp/yiyan.tmp || ! -e /tmp/yiyan.date ]];then
    echo "${nowdate}" > /tmp/yiyan.date
    #echo "$(curl -L -s https://sslapi.hitokoto.cn/?encode=text)" >> /tmp/yiyan.tmp
    echo "$(curl -L -s --connect-timeout 3 https://cn.fdos.me/yiyan/ || curl -L -s --connect-timeout 3 https://sslapi.hitokoto.cn/?encode=text)" >> /tmp/yiyan.tmp
    tail -n 1 /tmp/yiyan.tmp
else
    if [[ ${nowdate} == $(cat /tmp/yiyan.date) ]];then
        tail -n 1 /tmp/yiyan.tmp
    else
        echo "${nowdate}" > /tmp/yiyan.date
        #echo "$(curl -L -s https://sslapi.hitokoto.cn/?encode=text)" >> /tmp/yiyan.tmp
	echo "$(curl -L -s --connect-timeout 3 https://cn.fdos.me/yiyan/ || curl -L -s --connect-timeout 3 https://sslapi.hitokoto.cn/?encode=text || echo '无法连接到远程数据库!')" >> /tmp/yiyan.tmp
        tail -n 1 /tmp/yiyan.tmp
    fi
fi
}

checkup(){
	nowdate=$(date +%Y-%m-%d)
	if [[ ! -e ~/version.txt || ! -e /tmp/yiyan.date ]];then
		echo "${nowdate}" > /tmp/yiyan.date
		curl -s -L https://git.fdos.me/stack/AR-B-P-B/raw/develop/version.txt > ~/version.txt
		version1=`cat ~/version.txt`
	else
		if [[ ${nowdate} == $(cat /tmp/yiyan.date) ]];then
			version1=`cat ~/version.txt`
		else
			echo "${nowdate}" > /tmp/yiyan.date
			curl -s -L https://git.fdos.me/stack/AR-B-P-B/raw/develop/version.txt > ~/version.txt
			version1=`cat ~/version.txt`
		fi
	fi
	version2=`cat /usr/local/SSR-Bash-Python/version.txt`
	if [[ "$version1" == "$version2" ]];then
		echo " V${version2}"
	else
		echo "(有新版本 V${version1})"
	fi
}

killme(){
	for i in $(ps -ef | grep SSR-Bash-Python | awk '{print $2}')
	do
		kill -2 ${i}
	done
	kill -2 ssr 
	exit 0
}

addition(){
while read line;
do
    new=$(echo "${line}+${new}" | bc 2>/dev/null)
    if [[ -z ${new} ]];then
         new=${line}
    fi
done
echo "${new}"
}

#单位转换
convert(){
while read usage;
do
    if [ "${usage}" -gt 0 -a "${usage}" -lt 1024 ] ; then
		usage="${usage}B"
    elif [ "${usage}" -ge 1024 -a "${usage}" -lt 1048576 ] ; then
		usage="$(echo "scale=2; ${usage} / 1024" | bc)KB"
    elif [ "${usage}" -ge 1048576 -a "${usage}" -lt 1073741824 ] ; then
		usage="$(echo "scale=2; ${usage} / 1048576" | bc)MB"
    elif [ "${usage}" -ge 1073741824 -a "${usage}" -lt 1099511627776 ] ; then
		usage="$(echo "scale=2; ${usage} / 1073741824" | bc)GB"
    elif [ "${usage}" -ge 1099511627776 -a "${usage}" -lt 1125899906842624 ] ; then
		usage="$(echo "scale=2; ${usage} / 1099511627776" | bc)TB"
	elif [ "${usage}" -ge 1125899906842624 ] ; then
		usage="$(echo "scale=2; ${usage} / 1125899906842624" | bc)PB"
    fi
    echo "${usage}"
done
}

RX="$(cat /proc/net/dev | sed -n '/lo:/d;/:/p' | awk '{ print $2 }' | addition | convert )"
TX="$(cat /proc/net/dev | sed -n '/lo:/d;/:/p' | awk '{ print $10 }' | addition | convert)"

echo
echo "*******************"
echo ""
echo -e "欢迎使用 AR-B-P-B Beta\033[32m$(checkup)\033[0m\n"
echo -e "全局流量统计：发送:\033[40;34;1m${TX}\033[0m  接收:\033[40;34;1m${RX}\033[0m"
echo -e "每日一言：\033[32m$(yiyan)\033[0m\n"
echo "输入数字选择功能："
echo ""
echo "1.服务器控制"
echo "2.用户管理"
echo "3.全局流量管理"
echo "4.实验性功能"
echo "5.程序管理"
echo "6.一键添加用户(使用最优配置)"
echo "0.退出程序"
while :; do echo
	read -p "请选择： " choice
	if [[ ! $choice =~ ^[0-7]$ ]]; then
		echo "输入错误! 请输入正确的数字!"
	else
		echo 
		echo 
		break	
	fi
done

if [[ $choice == 0 ]];then
	killme 2&>/dev/null
fi

if [[ $choice == 1 ]];then
	bash /usr/local/SSR-Bash-Python/server.sh
fi

if [[ $choice == 2 ]];then
	bash /usr/local/SSR-Bash-Python/user.sh
fi

if [[ $choice == 3 ]];then
	bash /usr/local/SSR-Bash-Python/traffic.sh
fi

if [[ $choice == 4 ]];then
	bash /usr/local/SSR-Bash-Python/dev.sh
fi

if [[ $choice == 5 ]];then
	bash /usr/local/SSR-Bash-Python/self.sh
fi

if [[ $choice == 6 ]];then
	bash /usr/local/SSR-Bash-Python/user/easyadd.sh || exit 0
	ssr
	exit 0
fi

if [[ $choice == 7 ]];then
    bash /usr/local/SSR-Bash-Python/install.sh log
    ssr
fi
